/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package homepage;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import java.util.Vector;

/**
 *
 * @author berliana
 */
public class adminhomepage extends javax.swing.JFrame {

    /**
     * Creates new form adminhomepage
     */
    Connection conn = null;
    Statement st = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int x,i;
    String url = "jdbc:mysql://localhost:3306/oopfp";
    String user = "root";
    String pass = "";
    
    public adminhomepage() {
        initComponents();
        TeacherManager();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lbUsername = new javax.swing.JLabel();
        txtTeacherDepartment = new javax.swing.JTextField();
        lbName = new javax.swing.JLabel();
        lbDepartment = new javax.swing.JLabel();
        txtTeacherName = new javax.swing.JTextField();
        txtTeacherUsername = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTeacher = new javax.swing.JTable();
        bNewDataTeacher = new javax.swing.JButton();
        bUpdateDataTeacher = new javax.swing.JButton();
        bDeleteTeacher = new javax.swing.JButton();
        bResetTeacher = new javax.swing.JButton();
        bExit = new javax.swing.JButton();
        lbDepartment1 = new javax.swing.JLabel();
        txtTeacherPassword = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        lbUsername1 = new javax.swing.JLabel();
        txtStClass = new javax.swing.JTextField();
        lbName1 = new javax.swing.JLabel();
        lbDepartment2 = new javax.swing.JLabel();
        txtStName = new javax.swing.JTextField();
        txtStUsername = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbStudent = new javax.swing.JTable();
        bNewDataStudent = new javax.swing.JButton();
        bUpdateDataStudent = new javax.swing.JButton();
        bDeleteStudent = new javax.swing.JButton();
        bResetStudent = new javax.swing.JButton();
        bExitStudent = new javax.swing.JButton();
        lbDepartment3 = new javax.swing.JLabel();
        lbPasswordS = new javax.swing.JLabel();
        txtStPassword = new javax.swing.JPasswordField();
        txtStDepartment = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Admin Home Page", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 0, 36))); // NOI18N

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        lbUsername.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lbUsername.setText("NIP");

        txtTeacherDepartment.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        lbName.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lbName.setText("Nama");

        lbDepartment.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lbDepartment.setText("Prodi");

        txtTeacherName.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        txtTeacherUsername.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        tbTeacher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NIP", "Nama", "Prodi"
            }
        ));
        tbTeacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTeacherMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTeacher);

        bNewDataTeacher.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        bNewDataTeacher.setText("Add New Data");
        bNewDataTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNewDataTeacherActionPerformed(evt);
            }
        });

        bUpdateDataTeacher.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        bUpdateDataTeacher.setText("Update Data");
        bUpdateDataTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUpdateDataTeacherActionPerformed(evt);
            }
        });

        bDeleteTeacher.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        bDeleteTeacher.setText("Delete");
        bDeleteTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteTeacherActionPerformed(evt);
            }
        });

        bResetTeacher.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        bResetTeacher.setText("Reset");
        bResetTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetTeacherActionPerformed(evt);
            }
        });

        bExit.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        bExit.setText("Exit");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });

        lbDepartment1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lbDepartment1.setText("Password");

        txtTeacherPassword.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        txtTeacherPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeacherPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbName)
                            .addComponent(lbUsername))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTeacherName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTeacherUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDepartment1)
                            .addComponent(lbDepartment))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTeacherPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTeacherDepartment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bDeleteTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bNewDataTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                    .addComponent(bUpdateDataTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bResetTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbUsername)
                            .addComponent(txtTeacherUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbName)
                            .addComponent(txtTeacherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDepartment)
                            .addComponent(txtTeacherDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDepartment1)
                            .addComponent(txtTeacherPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(bNewDataTeacher)
                        .addGap(10, 10, 10)
                        .addComponent(bUpdateDataTeacher)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bResetTeacher)
                        .addGap(14, 14, 14)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bDeleteTeacher)
                        .addGap(138, 138, 138)
                        .addComponent(bExit))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Teacher", jPanel2);

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        lbUsername1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lbUsername1.setText("NIM");

        txtStClass.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        lbName1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lbName1.setText("Nama");

        lbDepartment2.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lbDepartment2.setText("Prodi");

        txtStName.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        txtStUsername.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        tbStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Prodi", "Kelas"
            }
        ));
        tbStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbStudentMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbStudent);

        bNewDataStudent.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        bNewDataStudent.setText("Add New Data");
        bNewDataStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNewDataStudentActionPerformed(evt);
            }
        });

        bUpdateDataStudent.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        bUpdateDataStudent.setText("Update Data");
        bUpdateDataStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUpdateDataStudentActionPerformed(evt);
            }
        });

        bDeleteStudent.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        bDeleteStudent.setText("Delete");
        bDeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteStudentActionPerformed(evt);
            }
        });

        bResetStudent.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        bResetStudent.setText("Reset");
        bResetStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetStudentActionPerformed(evt);
            }
        });

        bExitStudent.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        bExitStudent.setText("Exit");
        bExitStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitStudentActionPerformed(evt);
            }
        });

        lbDepartment3.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lbDepartment3.setText("Kelas");

        lbPasswordS.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lbPasswordS.setText("Password");

        txtStPassword.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        txtStPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStPasswordActionPerformed(evt);
            }
        });

        txtStDepartment.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbPasswordS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtStPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbName1)
                            .addComponent(lbUsername1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbDepartment2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtStDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbDepartment3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtStClass, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bDeleteStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bNewDataStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                    .addComponent(bUpdateDataStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bResetStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bExitStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbUsername1)
                            .addComponent(txtStUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbName1)
                            .addComponent(txtStName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(lbDepartment2)
                                .addGap(24, 24, 24)
                                .addComponent(lbDepartment3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(txtStDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtStClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(bNewDataStudent)
                        .addGap(10, 10, 10)
                        .addComponent(bUpdateDataStudent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bResetStudent)
                        .addGap(14, 14, 14)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bDeleteStudent)
                    .addComponent(txtStPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPasswordS, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bExitStudent, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(38, 38, 38))
        );

        jTabbedPane1.addTab("Student", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1094, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Class", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bNewDataTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNewDataTeacherActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(url, user, pass);
            pst = conn.prepareStatement("INSERT INTO TEACHER(USERNAME, NAME, DEPARTEMENT, PWD) VALUE (?,?,?,?)");
            pst.setString(1,txtTeacherUsername.getText());
            pst.setString(2,txtTeacherName.getText());
            pst.setString(3,txtTeacherDepartment.getText());
            pst.setString(4,String.valueOf(txtTeacherPassword.getPassword()));
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Ditambahkan");  
            
            TeacherManager();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_bNewDataTeacherActionPerformed

    private void bUpdateDataTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdateDataTeacherActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(url, user, pass);
            if(txtTeacherPassword.getText().length()==0){
                pst = conn.prepareStatement("UPDATE TEACHER SET USERNAME = ?, NAME = ?, DEPARTEMENT = ? WHERE USERNAME = ?");
                pst.setString(1,txtTeacherUsername.getText());
                pst.setString(2,txtTeacherName.getText());
                pst.setString(3,txtTeacherDepartment.getText());
                pst.setString(4,txtTeacherUsername.getText());
            }else{
                pst = conn.prepareStatement("UPDATE TEACHER SET USERNAME = ?, NAME = ?, DEPARTEMENT = ?, PWD = ? WHERE USERNAME = ?");
                pst.setString(1,txtTeacherUsername.getText());
                pst.setString(2,txtTeacherName.getText());
                pst.setString(3,txtTeacherDepartment.getText());
                pst.setString(4,String.valueOf(txtTeacherPassword.getPassword()));
                pst.setString(5,txtTeacherUsername.getText());
            }
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Diperbarui!");  
            TeacherManager();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_bUpdateDataTeacherActionPerformed

    private void bDeleteTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteTeacherActionPerformed
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel) tbTeacher.getModel();
        int selectedRow = tbTeacher.getSelectedRow();
        try{
            String uname = RecordTable.getValueAt(selectedRow,0).toString();
            Object[] options = {"Batal", "Konfirmasi"};
            int n = JOptionPane.showOptionDialog(this,
            "Apakah Anda yakin akan menghapus Data ini?",
            "Delete Confirmation",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE,
            null,     //do not use a custom Icon
            options,  //the titles of buttons
            options[0]); //default button title
            if(n==1){
                Class.forName("com.mysql.jdbc.Driver");
                conn = DriverManager.getConnection(url, user, pass);
                pst = conn.prepareStatement("DELETE FROM TEACHER WHERE USERNAME = ?");
                pst.setString(1,uname);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Telah Dihapus");  
                TeacherManager();
                txtTeacherDepartment.setText("");
                txtTeacherUsername.setText("");
                txtTeacherName.setText("");
                txtTeacherPassword.setText("");
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_bDeleteTeacherActionPerformed

    private void bResetTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetTeacherActionPerformed
        // TODO add your handling code here:
        txtTeacherDepartment.setText("");
        txtTeacherUsername.setText("");
        txtTeacherName.setText("");
        txtTeacherPassword.setText("");
    }//GEN-LAST:event_bResetTeacherActionPerformed

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        // TODO add your handling code here
        Object[] options = {"Batal", "Konfirmasi"};
        int n = JOptionPane.showOptionDialog(this,
            "Apakah Anda yakin akan Keluar?",
            "Exit Confirmation",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE,
            null,     //do not use a custom Icon
            options,  //the titles of buttons
            options[0]); //default button title
        if(n==1){
            System.exit(0);
        }
    }//GEN-LAST:event_bExitActionPerformed

    private void txtTeacherPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeacherPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeacherPasswordActionPerformed

    private void tbTeacherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTeacherMouseClicked
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel) tbTeacher.getModel();
        int selectedRow = tbTeacher.getSelectedRow();
        txtTeacherUsername.setText(RecordTable.getValueAt(selectedRow,0).toString());
        txtTeacherName.setText(RecordTable.getValueAt(selectedRow,1).toString());
        txtTeacherDepartment.setText(RecordTable.getValueAt(selectedRow,2).toString());
        txtTeacherPassword.setText(RecordTable.getValueAt(selectedRow,3).toString());
    }//GEN-LAST:event_tbTeacherMouseClicked

    private void tbStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbStudentMouseClicked
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel) tbStudent.getModel();
        int selectedRow = tbStudent.getSelectedRow();
        txtStUsername.setText(RecordTable.getValueAt(selectedRow,0).toString());
        txtStName.setText(RecordTable.getValueAt(selectedRow,1).toString());
        txtStDepartment.setText(RecordTable.getValueAt(selectedRow,2).toString());
        txtStClass.setText(RecordTable.getValueAt(selectedRow,3).toString());
        txtStPassword.setText(RecordTable.getValueAt(selectedRow,4).toString());
    }//GEN-LAST:event_tbStudentMouseClicked

    private void bNewDataStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNewDataStudentActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(url, user, pass);
            pst = conn.prepareStatement("INSERT INTO STUDENT (USERNAME, NAME, DEPARTEMENTID, CLASSID,PWD) VALUE (?,?,?,?,?)");
            pst.setString(1,txtStUsername.getText());
            pst.setString(2,txtStName.getText());
            pst.setString(3,txtStDepartment.getText());
            pst.setString(4,txtStClass.getText());
            pst.setString(5,String.valueOf(txtStPassword.getPassword()));
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Ditambahkan");  
            
            StudentManager();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_bNewDataStudentActionPerformed

    private void bUpdateDataStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdateDataStudentActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(url, user, pass);
            if(txtStPassword.getText().length()==0){
                pst = conn.prepareStatement("UPDATE STUDENT SET USERNAME = ?, NAME = ?, DEPARTEMENTID = ?, CLASSID = ? WHERE USERNAME = ?");
                pst.setString(1,txtStUsername.getText());
                pst.setString(2,txtStName.getText());
                pst.setString(3,txtStDepartment.getText());
                pst.setString(4,txtStClass.getText());
                pst.setString(5,txtStUsername.getText());
            }else{
                pst = conn.prepareStatement("UPDATE STUDENT SET USERNAME = ?, NAME = ?, DEPARTEMENTID = ?, CLASSID = ?, PWD = ? WHERE USERNAME = ?");
                pst.setString(1,txtStUsername.getText());
                pst.setString(2,txtStName.getText());
                pst.setString(3,txtStDepartment.getText());
                pst.setString(4,txtStClass.getText());
                pst.setString(5,String.valueOf(txtStPassword.getPassword()));
                pst.setString(6,txtStUsername.getText());
            }
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Diperbarui!");  
            TeacherManager();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_bUpdateDataStudentActionPerformed

    private void bDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteStudentActionPerformed
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel) tbStudent.getModel();
        int selectedRow = tbStudent.getSelectedRow();
        try{
            String uname = RecordTable.getValueAt(selectedRow,0).toString();
            Object[] options = {"Batal", "Konfirmasi"};
            int n = JOptionPane.showOptionDialog(this,
            "Apakah Anda yakin akan menghapus Data ini?",
            "Delete Confirmation",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE,
            null,     //do not use a custom Icon
            options,  //the titles of buttons
            options[0]); //default button title
            if(n==1){
                Class.forName("com.mysql.jdbc.Driver");
                conn = DriverManager.getConnection(url, user, pass);
                pst = conn.prepareStatement("DELETE FROM STUDENT WHERE USERNAME = ?");
                pst.setString(1,uname);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Telah Dihapus");  
                TeacherManager();
                txtStDepartment.setText("");
                txtStUsername.setText("");
                txtStName.setText("");
                txtStClass.setText("");
                txtTeacherPassword.setText("");
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_bDeleteStudentActionPerformed

    private void bResetStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetStudentActionPerformed
        // TODO add your handling code here:
        txtStDepartment.setText("");
        txtStUsername.setText("");
        txtStName.setText("");
        txtStClass.setText("");
        txtTeacherPassword.setText("");
    }//GEN-LAST:event_bResetStudentActionPerformed

    private void bExitStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitStudentActionPerformed
        // TODO add your handling code here:
        Object[] options = {"Batal", "Konfirmasi"};
        int n = JOptionPane.showOptionDialog(this,
            "Apakah Anda yakin akan Keluar?",
            "Exit Confirmation",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE,
            null,     //do not use a custom Icon
            options,  //the titles of buttons
            options[0]); //default button title
        if(n==1){
            System.exit(0);
        }
    }//GEN-LAST:event_bExitStudentActionPerformed

    private void txtStPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStPasswordActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
           // TODO add your handling code here:
           TeacherManager();
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        StudentManager();
        
    }//GEN-LAST:event_jPanel3MouseClicked
    
    private void TeacherManager(){
    try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(url, user, pass);
            pst = conn.prepareStatement("SELECT * FROM TEACHER");
            
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            x = stData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel) tbTeacher.getModel();
            RecordTable.setRowCount(0);
            
            while(rs.next()){
                Vector columnData = new Vector();
                for(i = 1; i<=x; i++){
                    columnData.add(rs.getString("USERNAME"));
                    columnData.add(rs.getString("NAME"));
                    columnData.add(rs.getString("DEPARTEMENT"));
                }
                RecordTable.addRow(columnData);
                
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());    
        }
    }
    /**
     * @param args the command line arguments
     */
    
    private void StudentManager(){
    try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(url, user, pass);
            pst = conn.prepareStatement("SELECT * FROM STUDENT");
            
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            x = stData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel) tbTeacher.getModel();
            RecordTable.setRowCount(0);
            
            while(rs.next()){
                Vector columnData = new Vector();
                for(i = 1; i<=x; i++){
                    columnData.add(rs.getString("USERNAME"));
                    columnData.add(rs.getString("NAME"));
                    columnData.add(rs.getString("DEPARTEMENTID"));
                    columnData.add(rs.getString("CLASSID"));
                }
                RecordTable.addRow(columnData);
                
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());    
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminhomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminhomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminhomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminhomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminhomepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDeleteStudent;
    private javax.swing.JButton bDeleteTeacher;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bExitStudent;
    private javax.swing.JButton bNewDataStudent;
    private javax.swing.JButton bNewDataTeacher;
    private javax.swing.JButton bResetStudent;
    private javax.swing.JButton bResetTeacher;
    private javax.swing.JButton bUpdateDataStudent;
    private javax.swing.JButton bUpdateDataTeacher;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbDepartment;
    private javax.swing.JLabel lbDepartment1;
    private javax.swing.JLabel lbDepartment2;
    private javax.swing.JLabel lbDepartment3;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbName1;
    private javax.swing.JLabel lbPasswordS;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JLabel lbUsername1;
    private javax.swing.JTable tbStudent;
    private javax.swing.JTable tbTeacher;
    private javax.swing.JTextField txtStClass;
    private javax.swing.JTextField txtStDepartment;
    private javax.swing.JTextField txtStName;
    private javax.swing.JPasswordField txtStPassword;
    private javax.swing.JTextField txtStUsername;
    private javax.swing.JTextField txtTeacherDepartment;
    private javax.swing.JTextField txtTeacherName;
    private javax.swing.JPasswordField txtTeacherPassword;
    private javax.swing.JTextField txtTeacherUsername;
    // End of variables declaration//GEN-END:variables
}
